{
 "title": "N35R05-WANSIM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top Sources and Destinations with Ports",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r._field == \"bytes\" or r._field == \"sampling_rate\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"src_ip\", \"src_port\", \"dst_ip\", \"dst_port\"])\r\n      \r\nbytes = data |> filter(fn: (r) => r._field == \"bytes\") |> sum() |> set(key: \"_field\", value: \"bytes\")\r\npackets = data |> filter(fn:(r) => r._field == \"sampling_rate\") |> sum() |> set(key: \"_field\",value: \"packets\")\r\nrecords = data |> filter(fn: (r) => r._field== \"bytes\") |> count() |> set(key: \"_field\", value: \"records\") \r\n\r\nunion(tables: [bytes, packets, records])\r\n  |> group()\r\n  |> pivot(rowKey:[\"src_ip\", \"src_port\", \"dst_ip\", \"dst_port\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns:[\"src_ip\", \"src_port\", \"dst_ip\", \"dst_port\", \"bytes\", \"packets\", \"records\"])\r\n  |> sort(columns:[\"bytes\"], desc:true)"
    }
   ]
  },
  {
   "title": "Traffic by Source and Destination IP",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns: [\"_time\", \"_value\",\"_field\",\"src_ip\",\"dst_ip\",\"host\"])\r\n  |> filter(fn: (r) => r._field == \"bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> sum(column: \"_value\"))"
    }
   ]
  },
  {
   "title": "Top Sources",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "data = from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r._field== \"bytes\" or r._field == \"sampling_rate\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"src_ip\", \"dst_port\", \"src_port\"])\r\n      \r\n  bytes = data |> filter(fn: (r) => r._field == \"bytes\") |> sum() |> set(key: \"_field\", value: \"bytes\")\r\n  packets = data |> filter(fn:(r) => r._field == \"sampling_rate\") |> sum() |> set(key: \"_field\",value: \"packets\")\r\n  records = data |> filter(fn: (r) => r._field== \"bytes\") |> count() |> set(key: \"_field\", value: \"records\") \r\n\r\n  union(tables: [bytes, packets, records])\r\n  |> group()\r\n  |> pivot(rowKey:[\"src_ip\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns:[\"bytes\"], desc:true)"
    }
   ]
  },
  {
   "title": "Top Destinations ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "data = from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r._field == \"bytes\" or r._field == \"sampling_rate\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"dst_ip\"])\r\n\r\nbytes = data |> filter(fn: (r) => r._field == \"bytes\") |> sum() |> set(key: \"_field\", value: \"bytes\")\r\npackets = data |> filter(fn:(r) => r._field == \"sampling_rate\") |> sum() |> set(key: \"_field\",value: \"packets\")\r\nrecords = data |> filter(fn: (r) => r._field== \"bytes\") |> count() |> set(key: \"_field\", value: \"records\") \r\n\r\nunion(tables: [bytes, packets, records])\r\n  |> group()\r\n  |> pivot(rowKey:[\"dst_ip\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns:[\"bytes\"], desc:true)"
    }
   ]
  },
  {
   "title": "Traffic by Source IP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns: [\"_time\", \"_value\",\"_field\",\"src_ip\",\"host\"])\r\n  |> filter(fn: (r) => r._field == \"bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> sum(column: \"_value\"))\r\n"
    }
   ]
  },
  {
   "title": "Traffic by Destination IP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sflow\")\r\n  |> filter(fn: (r) => r[\"src_ip\"] != \"10.10.32.129\" and r[\"dst_ip\"] != \"10.10.32.129\" )\r\n  |> keep(columns: [\"_time\", \"_value\",\"_field\",\"dst_ip\",\"host\"])\r\n  |> filter(fn: (r) => r._field == \"bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> sum(column: \"_value\"))"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"available\" or r[\"_field\"] == \"used\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Drops and Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"gre1\" or r[\"interface\"] == \"eth0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"drop_in\" or r[\"_field\"] == \"drop_out\" or r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> difference()"
    }
   ]
  },
  {
   "title": "Interface Packets Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\" or r[\"interface\"] == \"gre1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(nonNegative: true)\r\n"
    }
   ]
  },
  {
   "title": "Memory Percent Utilized",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\" or r[\"_field\"] == \"available_percent\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Utilization By Process",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"procstat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\" or r[\"interface\"] == \"gre1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"asrr1n25r08ws01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(nonNegative: true)"
    }
   ]
  }
 ]
}