# /etc/netplan/30_netplan_wansim.yaml
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    lo:
      addresses:
      - 127.0.0.1/8
      - "::1/128"
      - 11.11.11.11/32
    eth0:
      addresses:
      - 100.71.60.125/26
      mtu: 9216
      routes:
      - to: 0.0.0.0/0
        via: 100.71.60.65
      nameservers:
        addresses:
        - 10.50.10.50
        - 8.8.8.8
  tunnels:
    gre1:
      mode: gre
      local: 100.66.76.31
      remote: 100.71.85.123
      addresses:
      - 192.168.10.0/31
      mtu: 9000
    gre2:
      mode: gre
      local: 100.66.76.31
      remote: 100.71.85.124
      addresses:
      - 192.168.10.2/31
      mtu: 9000
