name: Build NetworkProfileGenerator

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/**.md'

jobs:

  build-project:

    strategy:
      matrix:
        GO_VERSION: [1.21]
        OS_WINDOWS: [windows]
        OS_LINUX: [linux]
        CODE_DIR: [./tools/NetworkProfileGenerator]
        ARTIFACT_NAME: [NetworkProfileGenerator]
        ARTIFACT_DIR: [NetworkProfileGenerator]

    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.GO_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Unit Test
      run: |
        cd ${{ matrix.CODE_DIR }}
        ls -R
        go mod tidy
        go test -v

    - name: Build Windows Artifact
      run: |
        cd ${{ matrix.CODE_DIR }}
        go mod tidy
        GOOS=${{ matrix.OS_WINDOWS }} GOARCH=amd64 go build -o ./${{ matrix.ARTIFACT_DIR }}/${{ matrix.OS_WINDOWS }}/

    - name: Build Linux Artifact
      run: |
        cd ${{ matrix.CODE_DIR }}
        go mod tidy
        GOOS=${{ matrix.OS_LINUX }} GOARCH=amd64 go build -o ./${{ matrix.ARTIFACT_DIR }}/${{ matrix.OS_LINUX }}/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.ARTIFACT_DIR }}
        path: ${{ matrix.CODE_DIR }}/${{ matrix.ARTIFACT_DIR }}/